//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace HOGW_PT_Dealer.CoreConnector {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoreConnectorWSSoap", Namespace="http://tempuri.org/")]
    public partial class CoreConnectorWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNextOrderSeqOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockOrdersBySeqOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockOrdersForCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockOrdersToChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBranchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderStatusBySeqOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateChangeOrderStatusBySeqOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCancelOrderStatusBySeqOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderStatusByOrderNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderNotesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersCompactOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSecuritiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSecurityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CoreConnectorWS() {
            this.Url = global::HOGW_PT_Dealer.Properties.Settings.Default.CoreConnector_CoreConnectorWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNextOrderSeqCompletedEventHandler GetNextOrderSeqCompleted;
        
        /// <remarks/>
        public event GetStockOrdersCompletedEventHandler GetStockOrdersCompleted;
        
        /// <remarks/>
        public event GetStockOrdersBySeqCompletedEventHandler GetStockOrdersBySeqCompleted;
        
        /// <remarks/>
        public event GetStockOrdersForCancelCompletedEventHandler GetStockOrdersForCancelCompleted;
        
        /// <remarks/>
        public event GetStockOrdersToChangeCompletedEventHandler GetStockOrdersToChangeCompleted;
        
        /// <remarks/>
        public event GetBranchesCompletedEventHandler GetBranchesCompleted;
        
        /// <remarks/>
        public event UpdateOrderStatusBySeqCompletedEventHandler UpdateOrderStatusBySeqCompleted;
        
        /// <remarks/>
        public event UpdateChangeOrderStatusBySeqCompletedEventHandler UpdateChangeOrderStatusBySeqCompleted;
        
        /// <remarks/>
        public event UpdateCancelOrderStatusBySeqCompletedEventHandler UpdateCancelOrderStatusBySeqCompleted;
        
        /// <remarks/>
        public event UpdateOrderStatusByOrderNoCompletedEventHandler UpdateOrderStatusByOrderNoCompleted;
        
        /// <remarks/>
        public event UpdateOrderStatusCompletedEventHandler UpdateOrderStatusCompleted;
        
        /// <remarks/>
        public event UpdateOrderNotesCompletedEventHandler UpdateOrderNotesCompleted;
        
        /// <remarks/>
        public event GetAllCustomersCompactCompletedEventHandler GetAllCustomersCompactCompleted;
        
        /// <remarks/>
        public event GetAllCustomersCompletedEventHandler GetAllCustomersCompleted;
        
        /// <remarks/>
        public event GetAllCustomersBalanceCompletedEventHandler GetAllCustomersBalanceCompleted;
        
        /// <remarks/>
        public event GetSecuritiesCompletedEventHandler GetSecuritiesCompleted;
        
        /// <remarks/>
        public event GetSecurityCompletedEventHandler GetSecurityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNextOrderSeq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNextOrderSeq() {
            object[] results = this.Invoke("GetNextOrderSeq", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNextOrderSeqAsync() {
            this.GetNextOrderSeqAsync(null);
        }
        
        /// <remarks/>
        public void GetNextOrderSeqAsync(object userState) {
            if ((this.GetNextOrderSeqOperationCompleted == null)) {
                this.GetNextOrderSeqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNextOrderSeqOperationCompleted);
            }
            this.InvokeAsync("GetNextOrderSeq", new object[0], this.GetNextOrderSeqOperationCompleted, userState);
        }
        
        private void OnGetNextOrderSeqOperationCompleted(object arg) {
            if ((this.GetNextOrderSeqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNextOrderSeqCompleted(this, new GetNextOrderSeqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockOrder[] GetStockOrders(string status) {
            object[] results = this.Invoke("GetStockOrders", new object[] {
                        status});
            return ((StockOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockOrdersAsync(string status) {
            this.GetStockOrdersAsync(status, null);
        }
        
        /// <remarks/>
        public void GetStockOrdersAsync(string status, object userState) {
            if ((this.GetStockOrdersOperationCompleted == null)) {
                this.GetStockOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockOrdersOperationCompleted);
            }
            this.InvokeAsync("GetStockOrders", new object[] {
                        status}, this.GetStockOrdersOperationCompleted, userState);
        }
        
        private void OnGetStockOrdersOperationCompleted(object arg) {
            if ((this.GetStockOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockOrdersCompleted(this, new GetStockOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockOrdersBySeq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockOrder[] GetStockOrdersBySeq(int lastSeq, string status) {
            object[] results = this.Invoke("GetStockOrdersBySeq", new object[] {
                        lastSeq,
                        status});
            return ((StockOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockOrdersBySeqAsync(int lastSeq, string status) {
            this.GetStockOrdersBySeqAsync(lastSeq, status, null);
        }
        
        /// <remarks/>
        public void GetStockOrdersBySeqAsync(int lastSeq, string status, object userState) {
            if ((this.GetStockOrdersBySeqOperationCompleted == null)) {
                this.GetStockOrdersBySeqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockOrdersBySeqOperationCompleted);
            }
            this.InvokeAsync("GetStockOrdersBySeq", new object[] {
                        lastSeq,
                        status}, this.GetStockOrdersBySeqOperationCompleted, userState);
        }
        
        private void OnGetStockOrdersBySeqOperationCompleted(object arg) {
            if ((this.GetStockOrdersBySeqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockOrdersBySeqCompleted(this, new GetStockOrdersBySeqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockOrdersForCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CoreStockOrderCancel[] GetStockOrdersForCancel() {
            object[] results = this.Invoke("GetStockOrdersForCancel", new object[0]);
            return ((CoreStockOrderCancel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockOrdersForCancelAsync() {
            this.GetStockOrdersForCancelAsync(null);
        }
        
        /// <remarks/>
        public void GetStockOrdersForCancelAsync(object userState) {
            if ((this.GetStockOrdersForCancelOperationCompleted == null)) {
                this.GetStockOrdersForCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockOrdersForCancelOperationCompleted);
            }
            this.InvokeAsync("GetStockOrdersForCancel", new object[0], this.GetStockOrdersForCancelOperationCompleted, userState);
        }
        
        private void OnGetStockOrdersForCancelOperationCompleted(object arg) {
            if ((this.GetStockOrdersForCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockOrdersForCancelCompleted(this, new GetStockOrdersForCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockOrdersToChange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CoreStockOrderChange[] GetStockOrdersToChange() {
            object[] results = this.Invoke("GetStockOrdersToChange", new object[0]);
            return ((CoreStockOrderChange[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockOrdersToChangeAsync() {
            this.GetStockOrdersToChangeAsync(null);
        }
        
        /// <remarks/>
        public void GetStockOrdersToChangeAsync(object userState) {
            if ((this.GetStockOrdersToChangeOperationCompleted == null)) {
                this.GetStockOrdersToChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockOrdersToChangeOperationCompleted);
            }
            this.InvokeAsync("GetStockOrdersToChange", new object[0], this.GetStockOrdersToChangeOperationCompleted, userState);
        }
        
        private void OnGetStockOrdersToChangeOperationCompleted(object arg) {
            if ((this.GetStockOrdersToChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockOrdersToChangeCompleted(this, new GetStockOrdersToChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBranches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Branch[] GetBranches() {
            object[] results = this.Invoke("GetBranches", new object[0]);
            return ((Branch[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBranchesAsync() {
            this.GetBranchesAsync(null);
        }
        
        /// <remarks/>
        public void GetBranchesAsync(object userState) {
            if ((this.GetBranchesOperationCompleted == null)) {
                this.GetBranchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBranchesOperationCompleted);
            }
            this.InvokeAsync("GetBranches", new object[0], this.GetBranchesOperationCompleted, userState);
        }
        
        private void OnGetBranchesOperationCompleted(object arg) {
            if ((this.GetBranchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBranchesCompleted(this, new GetBranchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderStatusBySeq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOrderStatusBySeq(int orderSeq, string newStatus, string notes) {
            object[] results = this.Invoke("UpdateOrderStatusBySeq", new object[] {
                        orderSeq,
                        newStatus,
                        notes});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderStatusBySeqAsync(int orderSeq, string newStatus, string notes) {
            this.UpdateOrderStatusBySeqAsync(orderSeq, newStatus, notes, null);
        }
        
        /// <remarks/>
        public void UpdateOrderStatusBySeqAsync(int orderSeq, string newStatus, string notes, object userState) {
            if ((this.UpdateOrderStatusBySeqOperationCompleted == null)) {
                this.UpdateOrderStatusBySeqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderStatusBySeqOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderStatusBySeq", new object[] {
                        orderSeq,
                        newStatus,
                        notes}, this.UpdateOrderStatusBySeqOperationCompleted, userState);
        }
        
        private void OnUpdateOrderStatusBySeqOperationCompleted(object arg) {
            if ((this.UpdateOrderStatusBySeqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderStatusBySeqCompleted(this, new UpdateOrderStatusBySeqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateChangeOrderStatusBySeq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateChangeOrderStatusBySeq(int orderSeq, string newStatus) {
            object[] results = this.Invoke("UpdateChangeOrderStatusBySeq", new object[] {
                        orderSeq,
                        newStatus});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateChangeOrderStatusBySeqAsync(int orderSeq, string newStatus) {
            this.UpdateChangeOrderStatusBySeqAsync(orderSeq, newStatus, null);
        }
        
        /// <remarks/>
        public void UpdateChangeOrderStatusBySeqAsync(int orderSeq, string newStatus, object userState) {
            if ((this.UpdateChangeOrderStatusBySeqOperationCompleted == null)) {
                this.UpdateChangeOrderStatusBySeqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateChangeOrderStatusBySeqOperationCompleted);
            }
            this.InvokeAsync("UpdateChangeOrderStatusBySeq", new object[] {
                        orderSeq,
                        newStatus}, this.UpdateChangeOrderStatusBySeqOperationCompleted, userState);
        }
        
        private void OnUpdateChangeOrderStatusBySeqOperationCompleted(object arg) {
            if ((this.UpdateChangeOrderStatusBySeqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateChangeOrderStatusBySeqCompleted(this, new UpdateChangeOrderStatusBySeqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCancelOrderStatusBySeq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateCancelOrderStatusBySeq(int orderSeq, string newStatus) {
            object[] results = this.Invoke("UpdateCancelOrderStatusBySeq", new object[] {
                        orderSeq,
                        newStatus});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCancelOrderStatusBySeqAsync(int orderSeq, string newStatus) {
            this.UpdateCancelOrderStatusBySeqAsync(orderSeq, newStatus, null);
        }
        
        /// <remarks/>
        public void UpdateCancelOrderStatusBySeqAsync(int orderSeq, string newStatus, object userState) {
            if ((this.UpdateCancelOrderStatusBySeqOperationCompleted == null)) {
                this.UpdateCancelOrderStatusBySeqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCancelOrderStatusBySeqOperationCompleted);
            }
            this.InvokeAsync("UpdateCancelOrderStatusBySeq", new object[] {
                        orderSeq,
                        newStatus}, this.UpdateCancelOrderStatusBySeqOperationCompleted, userState);
        }
        
        private void OnUpdateCancelOrderStatusBySeqOperationCompleted(object arg) {
            if ((this.UpdateCancelOrderStatusBySeqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCancelOrderStatusBySeqCompleted(this, new UpdateCancelOrderStatusBySeqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderStatusByOrderNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOrderStatusByOrderNo(string orderNo, string newStatus) {
            object[] results = this.Invoke("UpdateOrderStatusByOrderNo", new object[] {
                        orderNo,
                        newStatus});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderStatusByOrderNoAsync(string orderNo, string newStatus) {
            this.UpdateOrderStatusByOrderNoAsync(orderNo, newStatus, null);
        }
        
        /// <remarks/>
        public void UpdateOrderStatusByOrderNoAsync(string orderNo, string newStatus, object userState) {
            if ((this.UpdateOrderStatusByOrderNoOperationCompleted == null)) {
                this.UpdateOrderStatusByOrderNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderStatusByOrderNoOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderStatusByOrderNo", new object[] {
                        orderNo,
                        newStatus}, this.UpdateOrderStatusByOrderNoOperationCompleted, userState);
        }
        
        private void OnUpdateOrderStatusByOrderNoOperationCompleted(object arg) {
            if ((this.UpdateOrderStatusByOrderNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderStatusByOrderNoCompleted(this, new UpdateOrderStatusByOrderNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOrderStatus(string OrderDate, int OrderSeq, string newStatus) {
            object[] results = this.Invoke("UpdateOrderStatus", new object[] {
                        OrderDate,
                        OrderSeq,
                        newStatus});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderStatusAsync(string OrderDate, int OrderSeq, string newStatus) {
            this.UpdateOrderStatusAsync(OrderDate, OrderSeq, newStatus, null);
        }
        
        /// <remarks/>
        public void UpdateOrderStatusAsync(string OrderDate, int OrderSeq, string newStatus, object userState) {
            if ((this.UpdateOrderStatusOperationCompleted == null)) {
                this.UpdateOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderStatus", new object[] {
                        OrderDate,
                        OrderSeq,
                        newStatus}, this.UpdateOrderStatusOperationCompleted, userState);
        }
        
        private void OnUpdateOrderStatusOperationCompleted(object arg) {
            if ((this.UpdateOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderStatusCompleted(this, new UpdateOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderNotes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOrderNotes(int OrderSeq, string Notes) {
            object[] results = this.Invoke("UpdateOrderNotes", new object[] {
                        OrderSeq,
                        Notes});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderNotesAsync(int OrderSeq, string Notes) {
            this.UpdateOrderNotesAsync(OrderSeq, Notes, null);
        }
        
        /// <remarks/>
        public void UpdateOrderNotesAsync(int OrderSeq, string Notes, object userState) {
            if ((this.UpdateOrderNotesOperationCompleted == null)) {
                this.UpdateOrderNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderNotesOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderNotes", new object[] {
                        OrderSeq,
                        Notes}, this.UpdateOrderNotesOperationCompleted, userState);
        }
        
        private void OnUpdateOrderNotesOperationCompleted(object arg) {
            if ((this.UpdateOrderNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderNotesCompleted(this, new UpdateOrderNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomersCompact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerCompact[] GetAllCustomersCompact() {
            object[] results = this.Invoke("GetAllCustomersCompact", new object[0]);
            return ((CustomerCompact[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersCompactAsync() {
            this.GetAllCustomersCompactAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCustomersCompactAsync(object userState) {
            if ((this.GetAllCustomersCompactOperationCompleted == null)) {
                this.GetAllCustomersCompactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersCompactOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomersCompact", new object[0], this.GetAllCustomersCompactOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersCompactOperationCompleted(object arg) {
            if ((this.GetAllCustomersCompactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersCompactCompleted(this, new GetAllCustomersCompactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer[] GetAllCustomers() {
            object[] results = this.Invoke("GetAllCustomers", new object[0]);
            return ((Customer[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersAsync() {
            this.GetAllCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCustomersAsync(object userState) {
            if ((this.GetAllCustomersOperationCompleted == null)) {
                this.GetAllCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomers", new object[0], this.GetAllCustomersOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersOperationCompleted(object arg) {
            if ((this.GetAllCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersCompleted(this, new GetAllCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomersBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerBalance[] GetAllCustomersBalance() {
            object[] results = this.Invoke("GetAllCustomersBalance", new object[0]);
            return ((CustomerBalance[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersBalanceAsync() {
            this.GetAllCustomersBalanceAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCustomersBalanceAsync(object userState) {
            if ((this.GetAllCustomersBalanceOperationCompleted == null)) {
                this.GetAllCustomersBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersBalanceOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomersBalance", new object[0], this.GetAllCustomersBalanceOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersBalanceOperationCompleted(object arg) {
            if ((this.GetAllCustomersBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersBalanceCompleted(this, new GetAllCustomersBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSecurities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Securities[] GetSecurities(string CustomerID) {
            object[] results = this.Invoke("GetSecurities", new object[] {
                        CustomerID});
            return ((Securities[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSecuritiesAsync(string CustomerID) {
            this.GetSecuritiesAsync(CustomerID, null);
        }
        
        /// <remarks/>
        public void GetSecuritiesAsync(string CustomerID, object userState) {
            if ((this.GetSecuritiesOperationCompleted == null)) {
                this.GetSecuritiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSecuritiesOperationCompleted);
            }
            this.InvokeAsync("GetSecurities", new object[] {
                        CustomerID}, this.GetSecuritiesOperationCompleted, userState);
        }
        
        private void OnGetSecuritiesOperationCompleted(object arg) {
            if ((this.GetSecuritiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSecuritiesCompleted(this, new GetSecuritiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSecurity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Securities GetSecurity(string CustomerID, string StockCode) {
            object[] results = this.Invoke("GetSecurity", new object[] {
                        CustomerID,
                        StockCode});
            return ((Securities)(results[0]));
        }
        
        /// <remarks/>
        public void GetSecurityAsync(string CustomerID, string StockCode) {
            this.GetSecurityAsync(CustomerID, StockCode, null);
        }
        
        /// <remarks/>
        public void GetSecurityAsync(string CustomerID, string StockCode, object userState) {
            if ((this.GetSecurityOperationCompleted == null)) {
                this.GetSecurityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSecurityOperationCompleted);
            }
            this.InvokeAsync("GetSecurity", new object[] {
                        CustomerID,
                        StockCode}, this.GetSecurityOperationCompleted, userState);
        }
        
        private void OnGetSecurityOperationCompleted(object arg) {
            if ((this.GetSecurityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSecurityCompleted(this, new GetSecurityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockOrder {
        
        private string orderDateField;
        
        private string orderTimeField;
        
        private int orderSeqField;
        
        private string orderNoField;
        
        private string orderTypeField;
        
        private char orderSideField;
        
        private char boardTypeField;
        
        private string stockCodeField;
        
        private decimal orderVolumeField;
        
        private decimal orderPriceField;
        
        private decimal orderValueField;
        
        private decimal orderFeeField;
        
        private string customerIDField;
        
        private string branchCodeField;
        
        private string tradeCodeField;
        
        private string customerBranchCodeField;
        
        private string customerTradeCodeField;
        
        private string receivedByField;
        
        private string approvedByField;
        
        private char orderStatusField;
        
        private char alertCodeField;
        
        private string notesField;
        
        private System.Nullable<int> sessionField;
        
        private System.Nullable<System.DateTime> transactionDateField;
        
        private System.Nullable<int> refNoField;
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
            }
        }
        
        /// <remarks/>
        public int OrderSeq {
            get {
                return this.orderSeqField;
            }
            set {
                this.orderSeqField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public char OrderSide {
            get {
                return this.orderSideField;
            }
            set {
                this.orderSideField = value;
            }
        }
        
        /// <remarks/>
        public char BoardType {
            get {
                return this.boardTypeField;
            }
            set {
                this.boardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrderVolume {
            get {
                return this.orderVolumeField;
            }
            set {
                this.orderVolumeField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrderPrice {
            get {
                return this.orderPriceField;
            }
            set {
                this.orderPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrderValue {
            get {
                return this.orderValueField;
            }
            set {
                this.orderValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrderFee {
            get {
                return this.orderFeeField;
            }
            set {
                this.orderFeeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TradeCode {
            get {
                return this.tradeCodeField;
            }
            set {
                this.tradeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerBranchCode {
            get {
                return this.customerBranchCodeField;
            }
            set {
                this.customerBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTradeCode {
            get {
                return this.customerTradeCodeField;
            }
            set {
                this.customerTradeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReceivedBy {
            get {
                return this.receivedByField;
            }
            set {
                this.receivedByField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
            }
        }
        
        /// <remarks/>
        public char OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public char AlertCode {
            get {
                return this.alertCodeField;
            }
            set {
                this.alertCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Securities {
        
        private string stockCodeField;
        
        private int quatityField;
        
        /// <remarks/>
        public string StockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
            }
        }
        
        /// <remarks/>
        public int Quatity {
            get {
                return this.quatityField;
            }
            set {
                this.quatityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerBalance {
        
        private string customerIDField;
        
        private string customerNameVietField;
        
        private double balanceField;
        
        private double availBalanceField;
        
        private double blockBalanceField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNameViet {
            get {
                return this.customerNameVietField;
            }
            set {
                this.customerNameVietField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public double AvailBalance {
            get {
                return this.availBalanceField;
            }
            set {
                this.availBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double BlockBalance {
            get {
                return this.blockBalanceField;
            }
            set {
                this.blockBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private string customerIDField;
        
        private string customerNameVietField;
        
        private double balanceField;
        
        private double availBalanceField;
        
        private double blockBalanceField;
        
        private string branchCodeField;
        
        private string addressVietField;
        
        private string telField;
        
        private string mobilePhoneField;
        
        private string emailField;
        
        private string dOBField;
        
        private int brokerIDField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNameViet {
            get {
                return this.customerNameVietField;
            }
            set {
                this.customerNameVietField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public double AvailBalance {
            get {
                return this.availBalanceField;
            }
            set {
                this.availBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double BlockBalance {
            get {
                return this.blockBalanceField;
            }
            set {
                this.blockBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AddressViet {
            get {
                return this.addressVietField;
            }
            set {
                this.addressVietField = value;
            }
        }
        
        /// <remarks/>
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public int BrokerID {
            get {
                return this.brokerIDField;
            }
            set {
                this.brokerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerCompact {
        
        private string customerIDField;
        
        private string customerNameVietField;
        
        private double balanceField;
        
        private double availBalanceField;
        
        private double blockBalanceField;
        
        private string branchCodeField;
        
        private int brokerIDField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNameViet {
            get {
                return this.customerNameVietField;
            }
            set {
                this.customerNameVietField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public double AvailBalance {
            get {
                return this.availBalanceField;
            }
            set {
                this.availBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double BlockBalance {
            get {
                return this.blockBalanceField;
            }
            set {
                this.blockBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public int BrokerID {
            get {
                return this.brokerIDField;
            }
            set {
                this.brokerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Branch {
        
        private string branchCodeField;
        
        private string branchNameField;
        
        private string addressField;
        
        private string telField;
        
        private string faxField;
        
        private string bankAccountField;
        
        private string bankNameField;
        
        private string bankLocationField;
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccount {
            get {
                return this.bankAccountField;
            }
            set {
                this.bankAccountField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankLocation {
            get {
                return this.bankLocationField;
            }
            set {
                this.bankLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CoreStockOrderChange {
        
        private string orderDateField;
        
        private int orderSeqField;
        
        private string orderStatusField;
        
        private string customerIDNewField;
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public int OrderSeq {
            get {
                return this.orderSeqField;
            }
            set {
                this.orderSeqField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerIDNew {
            get {
                return this.customerIDNewField;
            }
            set {
                this.customerIDNewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CoreStockOrderCancel {
        
        private string orderDateField;
        
        private int orderSeqField;
        
        private string orderStatusField;
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public int OrderSeq {
            get {
                return this.orderSeqField;
            }
            set {
                this.orderSeqField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetNextOrderSeqCompletedEventHandler(object sender, GetNextOrderSeqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNextOrderSeqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNextOrderSeqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetStockOrdersCompletedEventHandler(object sender, GetStockOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetStockOrdersBySeqCompletedEventHandler(object sender, GetStockOrdersBySeqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockOrdersBySeqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockOrdersBySeqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetStockOrdersForCancelCompletedEventHandler(object sender, GetStockOrdersForCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockOrdersForCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockOrdersForCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CoreStockOrderCancel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CoreStockOrderCancel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetStockOrdersToChangeCompletedEventHandler(object sender, GetStockOrdersToChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockOrdersToChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockOrdersToChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CoreStockOrderChange[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CoreStockOrderChange[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetBranchesCompletedEventHandler(object sender, GetBranchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBranchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBranchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Branch[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Branch[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateOrderStatusBySeqCompletedEventHandler(object sender, UpdateOrderStatusBySeqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderStatusBySeqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderStatusBySeqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateChangeOrderStatusBySeqCompletedEventHandler(object sender, UpdateChangeOrderStatusBySeqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateChangeOrderStatusBySeqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateChangeOrderStatusBySeqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateCancelOrderStatusBySeqCompletedEventHandler(object sender, UpdateCancelOrderStatusBySeqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCancelOrderStatusBySeqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCancelOrderStatusBySeqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateOrderStatusByOrderNoCompletedEventHandler(object sender, UpdateOrderStatusByOrderNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderStatusByOrderNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderStatusByOrderNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateOrderStatusCompletedEventHandler(object sender, UpdateOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateOrderNotesCompletedEventHandler(object sender, UpdateOrderNotesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderNotesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderNotesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllCustomersCompactCompletedEventHandler(object sender, GetAllCustomersCompactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersCompactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersCompactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerCompact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerCompact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllCustomersCompletedEventHandler(object sender, GetAllCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllCustomersBalanceCompletedEventHandler(object sender, GetAllCustomersBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerBalance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerBalance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetSecuritiesCompletedEventHandler(object sender, GetSecuritiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSecuritiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSecuritiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Securities[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Securities[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetSecurityCompletedEventHandler(object sender, GetSecurityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSecurityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSecurityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Securities Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Securities)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591