//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataContractResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataContractResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS.Common.Resources.DataContractResources", typeof(DataContractResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia chi validation.
        /// </summary>
        internal static string BranchModel_Address_Validation {
            get {
                return ResourceManager.GetString("BranchModel_Address_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chi nhánh phải là 3 ký tự số.
        /// </summary>
        internal static string BranchModel_BranchCode_Validation {
            get {
                return ResourceManager.GetString("BranchModel_BranchCode_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name validation.
        /// </summary>
        internal static string BranchModel_BranchName_Validation {
            get {
                return ResourceManager.GetString("BranchModel_BranchName_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required.
        /// </summary>
        internal static string CredentialLoginModel_Password_Required {
            get {
                return ResourceManager.GetString("CredentialLoginModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username field is required.
        /// </summary>
        internal static string CredentialLoginModel_Username_Required {
            get {
                return ResourceManager.GetString("CredentialLoginModel_Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối lượng phải lớn hơn 0..
        /// </summary>
        internal static string CustodyModel_Quantity_Validation {
            get {
                return ResourceManager.GetString("CustodyModel_Quantity_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu chứng khoán lưu ký không phù hợp.
        /// </summary>
        internal static string CustodyModel_SubType_Validation {
            get {
                return ResourceManager.GetString("CustodyModel_SubType_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng khoán thông thường.
        /// </summary>
        internal static string Enum_ActivityType_Normal {
            get {
                return ResourceManager.GetString("Enum_ActivityType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng khoán hạn chế chuyển nhượng.
        /// </summary>
        internal static string Enum_ActivityType_RestictedStock {
            get {
                return ResourceManager.GetString("Enum_ActivityType_RestictedStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK phổ thông.
        /// </summary>
        internal static string Enum_AssetSubType_CommonStock {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_CommonStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        internal static string Enum_AssetSubType_None {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK ưu đãi cổ tức không biểu quyết.
        /// </summary>
        internal static string Enum_AssetSubType_PreferentialDividendUnVoteStock {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_PreferentialDividendUnVoteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK ưu đãi khác không biểu quyết.
        /// </summary>
        internal static string Enum_AssetSubType_PreferentialOtherVotingStock {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_PreferentialOtherVotingStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK ưu đãi hoàn lại không biểu quyết.
        /// </summary>
        internal static string Enum_AssetSubType_PreferentialRefundUnVoteStock {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_PreferentialRefundUnVoteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK ưu đãi biểu quyết.
        /// </summary>
        internal static string Enum_AssetSubType_PreferentialVotingStock {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_PreferentialVotingStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK HCCN.
        /// </summary>
        internal static string Enum_AssetSubType_RestictedStock {
            get {
                return ResourceManager.GetString("Enum_AssetSubType_RestictedStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện huỷ.
        /// </summary>
        internal static string Enum_CustodyRequestType_Cancel {
            get {
                return ResourceManager.GetString("Enum_CustodyRequestType_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện tạo mới.
        /// </summary>
        internal static string Enum_CustodyRequestType_New {
            get {
                return ResourceManager.GetString("Enum_CustodyRequestType_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình thường.
        /// </summary>
        internal static string Enum_MessagePriority_Normal {
            get {
                return ResourceManager.GetString("Enum_MessagePriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện khẩn.
        /// </summary>
        internal static string Enum_MessagePriority_Urgent {
            get {
                return ResourceManager.GetString("Enum_MessagePriority_Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổ tức không khấu trừ thuế tại TCPH.
        /// </summary>
        internal static string Enum_RateOption_DividendsNoTax {
            get {
                return ResourceManager.GetString("Enum_RateOption_DividendsNoTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổ tức khấu trừ thuế tại TCPH.
        /// </summary>
        internal static string Enum_RateOption_DividendsTax {
            get {
                return ResourceManager.GetString("Enum_RateOption_DividendsTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãi suất thanh toán.
        /// </summary>
        internal static string Enum_RateOption_Interest {
            get {
                return ResourceManager.GetString("Enum_RateOption_Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền mua không được chuyển nhượng.
        /// </summary>
        internal static string Enum_RightBuyType_NonRightTransferable {
            get {
                return ResourceManager.GetString("Enum_RightBuyType_NonRightTransferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền mua được chuyển nhượng.
        /// </summary>
        internal static string Enum_RightBuyType_RightAreTransferred {
            get {
                return ResourceManager.GetString("Enum_RightBuyType_RightAreTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trái phiếu.
        /// </summary>
        internal static string Enum_UnitType_BondsUnit {
            get {
                return ResourceManager.GetString("Enum_UnitType_BondsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổ phiếu, chứng chỉ quỹ.
        /// </summary>
        internal static string Enum_UnitType_StockUnit {
            get {
                return ResourceManager.GetString("Enum_UnitType_StockUnit", resourceCulture);
            }
        }
    }
}
