//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ chốt sales: &lt;span class=&quot;text-crm-regular&quot;&gt;{0} successed{3}/{1} Customers{3}&lt;/span&gt;=&lt;span class=&quot;text-crm-successed&quot;&gt;{2}%&lt;/span&gt;.
        /// </summary>
        internal static string CRM_CUSTOMER_COTS {
            get {
                return ResourceManager.GetString("CRM_CUSTOMER_COTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;span class=&quot;text-crm-regular&quot;&gt;{0} Customers {1}&lt;/span&gt;: &lt;span class=&quot;text-crm-Following&quot;&gt; {2} Potential&lt;/span&gt; ,&lt;span class=&quot;text-crm-successed&quot;&gt; {3} Successed&lt;/span&gt; ,&lt;span class=&quot;text-crm-finished&quot;&gt; {4} Client&lt;/span&gt;.
        /// </summary>
        internal static string CRM_CUSTOMER_LIST_TOTAL {
            get {
                return ResourceManager.GetString("CRM_CUSTOMER_LIST_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xãy ra lỗi trong lúc cập nhật, xem lỗi chi tiết hoặc liên hệ với Administrator.
        /// </summary>
        internal static string CRM_EDIT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CRM_EDIT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một số trường yêu cầu không được để trống hoặc không hợp lý với hệ thống.
        /// </summary>
        internal static string CRM_EDIT_ERROR_MESSAGE_BLANK {
            get {
                return ResourceManager.GetString("CRM_EDIT_ERROR_MESSAGE_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Total: {0} {1} - &lt;span class=&quot;text-crm-successed&quot;&gt; {2} Successed&lt;/span&gt; - &lt;span class=&quot;text-crm-regular&quot;&gt; {3} Following&lt;/span&gt;.
        /// </summary>
        internal static string CRM_EVENT_LIST_TOTAL {
            get {
                return ResourceManager.GetString("CRM_EVENT_LIST_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận chuyển.
        /// </summary>
        internal static string CRM_MOVE_CUS_TITLE {
            get {
                return ResourceManager.GetString("CRM_MOVE_CUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure move this customer to CRM system?.
        /// </summary>
        internal static string CRM_MOVE_FROM_CUS_CONTENT {
            get {
                return ResourceManager.GetString("CRM_MOVE_FROM_CUS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn chuyển khách hàng này qua hệ thống quản lý danh sách Customer không?.
        /// </summary>
        internal static string CRM_MOVE_TO_CUS_CONTENT {
            get {
                return ResourceManager.GetString("CRM_MOVE_TO_CUS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You Have total:  {0} Báo giá -&lt;span class=&quot;text-crm-regular&quot;&gt;  {1} Following &lt;/span&gt; -&lt;span class=&quot;text-crm-successed&quot;&gt; {2} Successed&lt;/span&gt; - &lt;span class=&quot;text-crm-finished&quot;&gt;{3} Huỷ&lt;/span&gt; .
        /// </summary>
        internal static string CRM_PRICE_LIST_TOTAL {
            get {
                return ResourceManager.GetString("CRM_PRICE_LIST_TOTAL", resourceCulture);
            }
        }
    }
}
