//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace SBSCore.HnxGateway {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GatewaySoap", Namespace="http://www.vics.com.vn")]
    public partial class Gateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTradingSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListForCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDayCanceledListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDayModifiedListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Gateway() {
            this.Url = global::SBSCore.Properties.Settings.Default.SBSCore_HnxGateway_Gateway;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTradingSessionCompletedEventHandler GetTradingSessionCompleted;
        
        /// <remarks/>
        public event GetListForCancelCompletedEventHandler GetListForCancelCompleted;
        
        /// <remarks/>
        public event CancelOrderCompletedEventHandler CancelOrderCompleted;
        
        /// <remarks/>
        public event GetDayCanceledListCompletedEventHandler GetDayCanceledListCompleted;
        
        /// <remarks/>
        public event GetDayModifiedListCompletedEventHandler GetDayModifiedListCompleted;
        
        /// <remarks/>
        public event ModifyOrderCompletedEventHandler ModifyOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vics.com.vn/GetTradingSession", RequestNamespace="http://www.vics.com.vn", ResponseNamespace="http://www.vics.com.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HnxTradingSession GetTradingSession(string boardCodeList) {
            object[] results = this.Invoke("GetTradingSession", new object[] {
                        boardCodeList});
            return ((HnxTradingSession)(results[0]));
        }
        
        /// <remarks/>
        public void GetTradingSessionAsync(string boardCodeList) {
            this.GetTradingSessionAsync(boardCodeList, null);
        }
        
        /// <remarks/>
        public void GetTradingSessionAsync(string boardCodeList, object userState) {
            if ((this.GetTradingSessionOperationCompleted == null)) {
                this.GetTradingSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTradingSessionOperationCompleted);
            }
            this.InvokeAsync("GetTradingSession", new object[] {
                        boardCodeList}, this.GetTradingSessionOperationCompleted, userState);
        }
        
        private void OnGetTradingSessionOperationCompleted(object arg) {
            if ((this.GetTradingSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTradingSessionCompleted(this, new GetTradingSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vics.com.vn/GetListForCancel", RequestNamespace="http://www.vics.com.vn", ResponseNamespace="http://www.vics.com.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HnxMsgOrder[] GetListForCancel(string customerId, string stockCode, string orderside) {
            object[] results = this.Invoke("GetListForCancel", new object[] {
                        customerId,
                        stockCode,
                        orderside});
            return ((HnxMsgOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListForCancelAsync(string customerId, string stockCode, string orderside) {
            this.GetListForCancelAsync(customerId, stockCode, orderside, null);
        }
        
        /// <remarks/>
        public void GetListForCancelAsync(string customerId, string stockCode, string orderside, object userState) {
            if ((this.GetListForCancelOperationCompleted == null)) {
                this.GetListForCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListForCancelOperationCompleted);
            }
            this.InvokeAsync("GetListForCancel", new object[] {
                        customerId,
                        stockCode,
                        orderside}, this.GetListForCancelOperationCompleted, userState);
        }
        
        private void OnGetListForCancelOperationCompleted(object arg) {
            if ((this.GetListForCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListForCancelCompleted(this, new GetListForCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vics.com.vn/CancelOrder", RequestNamespace="http://www.vics.com.vn", ResponseNamespace="http://www.vics.com.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelOrder(string orderNumber, string canceledBy) {
            this.Invoke("CancelOrder", new object[] {
                        orderNumber,
                        canceledBy});
        }
        
        /// <remarks/>
        public void CancelOrderAsync(string orderNumber, string canceledBy) {
            this.CancelOrderAsync(orderNumber, canceledBy, null);
        }
        
        /// <remarks/>
        public void CancelOrderAsync(string orderNumber, string canceledBy, object userState) {
            if ((this.CancelOrderOperationCompleted == null)) {
                this.CancelOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderOperationCompleted);
            }
            this.InvokeAsync("CancelOrder", new object[] {
                        orderNumber,
                        canceledBy}, this.CancelOrderOperationCompleted, userState);
        }
        
        private void OnCancelOrderOperationCompleted(object arg) {
            if ((this.CancelOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vics.com.vn/GetDayCanceledList", RequestNamespace="http://www.vics.com.vn", ResponseNamespace="http://www.vics.com.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HnxMsgOrder[] GetDayCanceledList() {
            object[] results = this.Invoke("GetDayCanceledList", new object[0]);
            return ((HnxMsgOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDayCanceledListAsync() {
            this.GetDayCanceledListAsync(null);
        }
        
        /// <remarks/>
        public void GetDayCanceledListAsync(object userState) {
            if ((this.GetDayCanceledListOperationCompleted == null)) {
                this.GetDayCanceledListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDayCanceledListOperationCompleted);
            }
            this.InvokeAsync("GetDayCanceledList", new object[0], this.GetDayCanceledListOperationCompleted, userState);
        }
        
        private void OnGetDayCanceledListOperationCompleted(object arg) {
            if ((this.GetDayCanceledListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDayCanceledListCompleted(this, new GetDayCanceledListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vics.com.vn/GetDayModifiedList", RequestNamespace="http://www.vics.com.vn", ResponseNamespace="http://www.vics.com.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HnxMsgOrder[] GetDayModifiedList() {
            object[] results = this.Invoke("GetDayModifiedList", new object[0]);
            return ((HnxMsgOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDayModifiedListAsync() {
            this.GetDayModifiedListAsync(null);
        }
        
        /// <remarks/>
        public void GetDayModifiedListAsync(object userState) {
            if ((this.GetDayModifiedListOperationCompleted == null)) {
                this.GetDayModifiedListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDayModifiedListOperationCompleted);
            }
            this.InvokeAsync("GetDayModifiedList", new object[0], this.GetDayModifiedListOperationCompleted, userState);
        }
        
        private void OnGetDayModifiedListOperationCompleted(object arg) {
            if ((this.GetDayModifiedListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDayModifiedListCompleted(this, new GetDayModifiedListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vics.com.vn/ModifyOrder", RequestNamespace="http://www.vics.com.vn", ResponseNamespace="http://www.vics.com.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModifyOrder(string orderNumber, decimal oldVolume, decimal newPrice, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> newVolume, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> newStopPrice, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> newIcebergVolume) {
            this.Invoke("ModifyOrder", new object[] {
                        orderNumber,
                        oldVolume,
                        newPrice,
                        newVolume,
                        newStopPrice,
                        newIcebergVolume});
        }
        
        /// <remarks/>
        public void ModifyOrderAsync(string orderNumber, decimal oldVolume, decimal newPrice, System.Nullable<decimal> newVolume, System.Nullable<decimal> newStopPrice, System.Nullable<decimal> newIcebergVolume) {
            this.ModifyOrderAsync(orderNumber, oldVolume, newPrice, newVolume, newStopPrice, newIcebergVolume, null);
        }
        
        /// <remarks/>
        public void ModifyOrderAsync(string orderNumber, decimal oldVolume, decimal newPrice, System.Nullable<decimal> newVolume, System.Nullable<decimal> newStopPrice, System.Nullable<decimal> newIcebergVolume, object userState) {
            if ((this.ModifyOrderOperationCompleted == null)) {
                this.ModifyOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyOrderOperationCompleted);
            }
            this.InvokeAsync("ModifyOrder", new object[] {
                        orderNumber,
                        oldVolume,
                        newPrice,
                        newVolume,
                        newStopPrice,
                        newIcebergVolume}, this.ModifyOrderOperationCompleted, userState);
        }
        
        private void OnModifyOrderOperationCompleted(object arg) {
            if ((this.ModifyOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vics.com.vn")]
    public partial class HnxTradingSession {
        
        private TradingSessionMode tradingSessionModeField;
        
        private TradingSessionStatus tradingSessionStatusField;
        
        /// <remarks/>
        public TradingSessionMode TradingSessionMode {
            get {
                return this.tradingSessionModeField;
            }
            set {
                this.tradingSessionModeField = value;
            }
        }
        
        /// <remarks/>
        public TradingSessionStatus TradingSessionStatus {
            get {
                return this.tradingSessionStatusField;
            }
            set {
                this.tradingSessionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vics.com.vn")]
    public enum TradingSessionMode {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        OPEN,
        
        /// <remarks/>
        CONT,
        
        /// <remarks/>
        CLOSE,
        
        /// <remarks/>
        PCCLOSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vics.com.vn")]
    public enum TradingSessionStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        RamdomEnd,
        
        /// <remarks/>
        CbPending,
        
        /// <remarks/>
        AfterCb,
        
        /// <remarks/>
        Prolong,
        
        /// <remarks/>
        EndDay,
        
        /// <remarks/>
        Waiting,
        
        /// <remarks/>
        Closed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vics.com.vn")]
    public partial class HnxMsgOrder {
        
        private string clOrdIDField;
        
        private decimal modiPriceField;
        
        private decimal modiVolumeField;
        
        private decimal modiIoVolumeField;
        
        private string statusField;
        
        /// <remarks/>
        public string ClOrdID {
            get {
                return this.clOrdIDField;
            }
            set {
                this.clOrdIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal ModiPrice {
            get {
                return this.modiPriceField;
            }
            set {
                this.modiPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ModiVolume {
            get {
                return this.modiVolumeField;
            }
            set {
                this.modiVolumeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ModiIoVolume {
            get {
                return this.modiIoVolumeField;
            }
            set {
                this.modiIoVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTradingSessionCompletedEventHandler(object sender, GetTradingSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTradingSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTradingSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HnxTradingSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HnxTradingSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetListForCancelCompletedEventHandler(object sender, GetListForCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListForCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListForCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HnxMsgOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HnxMsgOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CancelOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDayCanceledListCompletedEventHandler(object sender, GetDayCanceledListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDayCanceledListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDayCanceledListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HnxMsgOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HnxMsgOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDayModifiedListCompletedEventHandler(object sender, GetDayModifiedListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDayModifiedListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDayModifiedListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HnxMsgOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HnxMsgOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ModifyOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591