<?xml version="1.0" encoding="utf-8"?>
<Database Name="SBS30" Class="CoreDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=10.10.2.3\db01_sqlserver;Initial Catalog=SBS30;Persist Security Info=True;User ID=sa" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StockOrder" Member="StockOrders">
    <Type Name="StockOrder">
      <Column Name="OrderDate" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderTime" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="OrderSeq" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OrderType" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="OrderSide" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="BoardType" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="StockCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="OrderVolume" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="OrderPrice" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="OrderValue" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Column Name="OrderFee" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BranchCode" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="TradeCode" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerBranchCode" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CustomerTradeCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ReceivedBy" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedBy" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OrderStatus" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="AlertCode" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Session" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="RefNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Branch" Member="Branches">
    <Type Name="Branch">
      <Column Name="BranchCode" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BankLocation" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>