version: '2.1'

services:
  ssm:
    image: ssm:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - :C:\inetpub\wwwroot
      - ~\msvsmon:C:\msvsmon:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
